# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shwDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shwDemo
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  

  target 'shwDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'shwDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shwDemo-tvOS

  target 'shwDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
